spring.application.name=techback

# ConfiguraÃ§Ãµes de erro
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/techback
spring.datasource.username=postgres
spring.datasource.password=heg5883
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto: create, create-drop, validate, update, none
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

# JPA specific configs
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql=true

#Integração ViaCEP
viacep.url=https://viacep.com.br/ws

#Integração BrasilApi
brasilapi.url=https://brasilapi.com.br

#Integração Receita Federal do Brasil
receitafederal.url=https://receitaws.com.br