-- =====================================================
-- TABELA FILME
-- =====================================================
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('14', '2023-05-15', 148, 'Ficção Científica', 'Um explorador espacial descobre um planeta onde o tempo passa de forma diferente.', 'Horizonte Estelar');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('L', '2022-10-10', 95, 'Animação', 'Uma pequena engrenagem ganha vida e tenta encontrar seu lugar em uma metrópole futurista.', 'O Pequeno Robô');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('16', '2024-01-20', 120, 'Suspense', 'Um detetive aposentado é forçado a resolver um último caso ligado ao seu passado.', 'Sombras do Ontem');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('12', '2023-08-05', 110, 'Aventura', 'Um grupo de arqueólogos encontra uma cidade perdida no coração da Amazônia.', 'O Tesouro Perdido');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('18', '2023-11-12', 135, 'Terror', 'Eventos inexplicáveis começam a ocorrer em um asilo abandonado durante o inverno.', 'O Grito do Silêncio');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('L', '2022-04-30', 105, 'Comédia', 'Dois vizinhos rivais precisam unir forças para organizar a festa do bairro.', 'Guerra das Cercas');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('14', '2024-02-14', 118, 'Drama', 'A história de superação de um pianista que perde a audição no auge da carreira.', 'Notas de Esperança');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('10', '2023-07-22', 125, 'Fantasia', 'Uma jovem descobre que é a herdeira de um reino subaquático em perigo.', 'Reino de Coral');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('16', '2023-09-30', 142, 'Policial', 'Um infiltrado em uma organização criminosa começa a questionar sua própria moralidade.', 'Linha de Fogo');
INSERT INTO FILME (CLASSIFICACAO_INDICATIVA, DATA_LANCAMENTO, DURACAO_MINUTOS, GENERO, SINOPSE, TITULO) VALUES ('12', '2024-03-01', 90, 'Documentário', 'Uma análise profunda sobre o impacto das tecnologias de IA na educação moderna.', 'Mentes Digitais');

-- =====================================================
-- TABELA FUNCIONARIO
-- =====================================================
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Ana Beatriz Silva', 'Gerente de Projetos');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Carlos Eduardo Santos', 'Desenvolvedor Backend Senior');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Mariana Oliveira Souza', 'Designer de UX/UI');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Ricardo Pereira Lima', 'Analista de Sistemas');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Fernanda Costa Melo', 'Coordenadora de RH');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Gabriel Alencar Rocha', 'Desenvolvedor Frontend Junior');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Juliana Martins Ferreira', 'Cientista de Dados');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Lucas Bittencourt', 'Administrador de Banco de Dados');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Patrícia Gomes Neves', 'Analista de Marketing Digital');
INSERT INTO FUNCIONARIO (NOME, CARGO) VALUES ('Thiago Augusto Viana', 'Engenheiro de DevOps');

-- =====================================================
-- TABELA PLANO
-- =====================================================
INSERT INTO PLANO (CODIGO, LIMITE_DIARIO, STREAMS_SIMULTANEOS) VALUES ('BASICO', 120, 1);
INSERT INTO PLANO (CODIGO, LIMITE_DIARIO, STREAMS_SIMULTANEOS) VALUES ('PREMIUM', 480, 4);
INSERT INTO PLANO (CODIGO, LIMITE_DIARIO, STREAMS_SIMULTANEOS) VALUES ('PROFISSIONAL', 1440, 10);

-- =====================================================
-- TABELA USUARIO
-- =====================================================
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('João Silva Santos', '1990-05-15', 'joao.silva@emailcom', 'k7*A+N1.vP8-r&Z', '05628491043', 'USER', '2024-01-10 10:30:00', '2024-01-10 10:30:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Maria Oliveira Costa', '1985-08-22', 'maria.oliveira@emailcom', '9.zR+4m&K*2-LqG', '48291530072', 'USER', '2024-01-12 14:15:00', '2024-01-12 14:15:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Pedro Ferreira Lima', '1992-03-10', 'pedro.ferreira@emailcom', 'B1-s.v8*Xp5+n&A', '83106254015', 'ADMIN', '2024-01-15 09:45:00', '2024-01-15 09:45:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Ana Carolina Mendes', '1988-11-30', 'ana.carolina@emailcom', 'r&Z9+2*Lm.4-KqP', '27419368020', 'USER', '2024-01-18 16:20:00', '2024-01-18 16:20:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Lucas Martins Rocha', '1995-07-08', 'lucas.martins@emailcom', 'v*8N1.p+G5-s&B', '91582743084', 'USER', '2024-02-01 11:30:00', '2024-02-01 11:30:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Beatriz Sousa Alves', '1991-12-25', 'beatriz.sousa@emailcom', 'Xp5+n.v8*s&B1-z', '10257389066', 'USER', '2024-02-05 13:15:00', '2024-02-05 13:15:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Carlos Augusto Neves', '1987-06-14', 'carlos.augusto@emailcom', '4-KqP9.zR+2*Lm&', '64731925009', 'USER', '2024-02-10 15:45:00', '2024-02-10 15:45:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Juliana Gomes Barbosa', '1993-09-19', 'juliana.gomes@emailcom', 'G5-s&B1.v*8N1+p', '39846217051', 'USER', '2024-02-15 10:00:00', '2024-02-15 10:00:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Rafael Pereira Oliveira', '1989-04-05', 'rafael.pereira@emailcom', '2*Lm&4-KqP9.zR+', '52073481098', 'USER', '2024-02-20 12:30:00', '2024-02-20 12:30:00');
INSERT INTO USUARIO (NOME_COMPLETO, DATA_NASCIMENTO, EMAIL, SENHA_HASH, CPF_CNPJ, PERFIL, CRIADO_EM, ATUALIZADO_EM) VALUES ('Fernanda Vieira Santos', '1994-10-12', 'fernanda.vieira@emailcom', 'n.v8*s&B1-zXp5+', '76315024037', 'USER', '2024-02-25 14:00:00', '2024-02-25 14:00:00');

-- =====================================================
-- TABELA METODO_PAGAMENTO
-- =====================================================
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (1, 'VISA', '1234', 12, 2025, 'JOAO S SANTOS', 'token_gateway_001', '2024-01-10');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (2, 'MASTERCARD', '5678', 6, 2026, 'MARIA O COSTA', 'token_gateway_002', '2024-01-12');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (3, 'VISA', '9012', 8, 2025, 'PEDRO F LIMA', 'token_gateway_003', '2024-01-15');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (4, 'ELO', '3456', 4, 2027, 'ANA C MENDES', 'token_gateway_004', '2024-01-18');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (5, 'VISA', '7890', 10, 2026, 'LUCAS M ROCHA', 'token_gateway_005', '2024-02-01');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (6, 'MASTERCARD', '2345', 2, 2025, 'BEATRIZ S ALVES', 'token_gateway_006', '2024-02-05');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (7, 'VISA', '6789', 9, 2027, 'CARLOS A NEVES', 'token_gateway_007', '2024-02-10');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (8, 'ELO', '0123', 7, 2026, 'JULIANA G BARBOSA', 'token_gateway_008', '2024-02-15');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (9, 'VISA', '4567', 11, 2025, 'RAFAEL P OLIVEIRA', 'token_gateway_009', '2024-02-20');
INSERT INTO METODO_PAGAMENTO (USUARIO_ID, BANDEIRA, ULTIMOS4, MES_EXP, ANO_EXP, NOME_PORTADOR, TOKEN_GATEWAY, CRIADO_EM) VALUES (10, 'MASTERCARD', '8901', 3, 2026, 'FERNANDA V SANTOS', 'token_gateway_010', '2024-02-25');

-- =====================================================
-- TABELA ASSINATURA
-- =====================================================
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (1, 1, 'ATIVA', '2024-01-10', NULL);
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (2, 2, 'ATIVA', '2024-01-12', NULL);
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (3, 3, 'ATIVA', '2024-01-15', NULL);
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (4, 1, 'EM_ATRASO', '2024-01-18', NULL);
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (5, 2, 'ATIVA', '2024-02-01', NULL);
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (6, 1, 'ATIVA', '2024-02-05', NULL);
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (7, 2, 'CANCELADA', '2024-02-10', '2024-03-15');
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (8, 3, 'ATIVA', '2024-02-15', NULL);
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (9, 1, 'ATIVA', '2024-02-20', NULL);
INSERT INTO ASSINATURA (USUARIO_ID, PLANO_ID, STATUS, INICIADA_EM, CANCELADA_EM) VALUES (10, 2, 'ATIVA', '2024-02-25', NULL);

-- =====================================================
-- TABELA CONTEUDO
-- =====================================================
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Série Mistério', 'SERIE', 2023, 45, 85, 'Uma série emocionante sobre detectives resolvendo casos inexplicáveis', 'https://trailerexamplecom/01', 'Suspense', '2024-01-05', '2024-01-05');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Série Comédia', 'SERIE', 2024, 25, 78, 'Uma série cômica sobre amigos e suas aventuras no trabalho', 'https://trailerexamplecom/02', 'Comédia', '2024-01-08', '2024-01-08');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Série Drama', 'SERIE', 2023, 60, 92, 'Uma série dramática sobre a vida na medicina moderna', 'https://trailerexamplecom/03', 'Drama', '2024-01-10', '2024-01-10');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Filme Aventura', 'FILME', 2023, 120, 87, 'Um filme de ação sobre exploradores em busca de um tesouro', 'https://trailerexamplecom/04', 'Aventura', '2024-01-12', '2024-01-12');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Filme Ficção', 'FILME', 2024, 140, 90, 'Um filme de ficção científica sobre viagens no tempo', 'https://trailerexamplecom/05', 'Ficção Científica', '2024-01-15', '2024-01-15');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Série Fantasia', 'SERIE', 2023, 55, 89, 'Uma série de fantasia épica com magia e dragões', 'https://trailerexamplecom/06', 'Fantasia', '2024-01-18', '2024-01-18');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Filme Thriller', 'FILME', 2023, 105, 83, 'Um filme de suspense sobre um serial killer', 'https://trailerexamplecom/07', 'Suspense', '2024-01-20', '2024-01-20');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Série Romance', 'SERIE', 2024, 35, 75, 'Uma série romântica sobre encontros e desencontros', 'https://trailerexamplecom/08', 'Romance', '2024-01-22', '2024-01-22');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Filme Ação', 'FILME', 2024, 130, 86, 'Um filme de ação com perseguições espetaculares', 'https://trailerexamplecom/09', 'Ação', '2024-01-25', '2024-01-25');
INSERT INTO CONTEUDO (TITULO, TIPO, ANO, DURACAO_MINUTOS, RELEVANCIA, SINOPSE, TRAILER_URL, GENERO, CRIADO_EM, ATUALIZADO_EM) VALUES ('Série Terror', 'SERIE', 2023, 50, 81, 'Uma série de terror baseada em histórias reais assustadoras', 'https://trailerexamplecom/10', 'Terror', '2024-01-28', '2024-01-28');

-- =====================================================
-- TABELA FAVORITO
-- =====================================================
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (1, 1, '2024-01-11');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (1, 4, '2024-01-13');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (2, 2, '2024-01-13');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (2, 5, '2024-01-16');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (3, 3, '2024-01-16');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (3, 6, '2024-01-19');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (4, 7, '2024-01-19');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (5, 8, '2024-02-02');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (6, 9, '2024-02-06');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (7, 10, '2024-02-11');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (8, 1, '2024-02-16');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (9, 4, '2024-02-21');
INSERT INTO FAVORITO (USUARIO_ID, CONTEUDO_ID, CRIADO_EM) VALUES (10, 5, '2024-02-26');

-- =====================================================
-- TABELA EVENTO_ASSISTIDO
-- =====================================================
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (1, 1, '2024-01-11');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (1, 4, '2024-01-14');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (2, 2, '2024-01-13');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (2, 5, '2024-01-17');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (2, 8, '2024-02-02');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (3, 3, '2024-01-16');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (3, 6, '2024-01-20');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (4, 7, '2024-01-19');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (5, 8, '2024-02-03');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (5, 9, '2024-02-07');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (6, 9, '2024-02-07');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (7, 10, '2024-02-11');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (8, 1, '2024-02-17');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (8, 3, '2024-02-18');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (9, 4, '2024-02-22');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (10, 5, '2024-02-27');
INSERT INTO EVENTO_ASSISTIDO (USUARIO_ID, CONTEUDO_ID, ASSISTIDO_EM) VALUES (10, 2, '2024-02-28');
